routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\User\ArticleUserController;
use App\Http\Controllers\User\CategoryUserController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Writer\TagController;
use App\Http\Controllers\Writer\ArticleWriterController;
use App\Http\Controllers\User\LikeController;
use App\Http\Controllers\User\CommentController;
use App\Http\Controllers\languageController;
use App\Http\Controllers\SocializationController;

//Route user dont need to login
Route::get('/', [ArticleUserController::class, 'index'])->name('homepage');
Route::get('/category/detail/{id}', [CategoryUserController::class, 'detail'])->name('detail.category');
Route::get('/article/detail/{id}', [ArticleUserController::class, 'show'])->name('show.article');
Route::get('/article/search', [ArticleUserController::class, 'search'])->name('article.search.user');
//route to stranslate
Route::get('/translate/{language}', [LanguageController::class, 'translate'])->name('translate.language');
//route to login with google
Route::get('/redirect/google', [SocializationController::class, 'redirectGoogle'])->name('redirect.google');
Route::get('/auth/google/callback', [SocializationController::class, 'callback']);


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    // make a read
    Route::get('/makeRead/{notification}', [NotificationController::class, 'makeRead'])->name('makeRead');
    //route like an article
    Route::post('/articles/{articleId}/like', [LikeController::class, 'likePost'])->name('like');
    Route::delete('/articles/{articleId}/like', [LikeController::class, 'unlikePost'])->name('unlike');
    Route::resources([
        'comment' => CommentController::class,
    ]);
});

//Route of writer role
Route::prefix('writer')->middleware(['auth', 'checkRole:Writer'])->group(function () {
    Route::post('upload-textImage1', [ArticleWriterController::class, 'uploadTextImage'])->name('content.image.upload1');
    Route::resources([
        'writerArticle' => ArticleWriterController::class,
    ]);
});


//Route of admin role
Route::prefix('admin')->middleware(['auth', 'checkRole:Admin'])->group(function () {
    //Article controller route
    Route::get('edit-post', [ArticleController::class, 'edit2'])->name('edit2');
    Route::get('/create/article', [ArticleController::class, 'crate'])->name('article.create.differ');
    Route::get('/list-schedule', [ArticleController::class, 'listSchedule'])->name('article.list.schedule');
    Route::get('/create-schedule', [ArticleController::class, 'createSchedule'])->name('article.create.schedule');
    Route::post('/store-schedule', [ArticleController::class, 'storeSchedule'])->name('article.store.schedule');
    Route::get('/search-article', [ArticleController::class, 'search'])->name('article.search');
    Route::post('upload-textImage', [ArticleController::class, 'uploadTextImage'])->name('content.image.upload');

    //Routes to search by model filler
    Route::get('/search-user', [UserController::class, 'search'])->name('user.search');
    Route::get('/search-tag', [TagController::class, 'search'])->name('tag.search');
    Route::get('/search-category', [CategoryController::class, 'search'])->name('category.search');
    Route::get('/searc-notification', [NotificationController::class, 'search'])->name('notification.search');

    //all route resource
    Route::resources([
        'categories' => CategoryController::class,
        'users' => UserController::class,
        'article' => ArticleController::class,
        'notification' => NotificationController::class,
        'tag' => TagController::class,
    ]);
});

require __DIR__ . '/auth.php';

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use App\Models\Category;
use App\Models\Article;
use App\Http\Requests\ArticleRequest;
use App\Http\Requests\ArticleUpdateRequest;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;


class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     */

    public function index()
    {
        $articles = Article::with('tags')->get();
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.article.index', compact('articles', 'categories', 'tags'));
    }

    public function listSchedule()
    {
        $articles = Article::where('status', 'dislable')->get();
        return view('admin.article.ListTaskSchedule', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function createSchedule()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.article.createSchedule', compact('categories', 'tags'));
    }

    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('admin.article.createArticle', compact('categories', 'tags'));
    }

    //upload image text edittor
    public function uploadTextImage(Request $request)
    {
        if ($request->hasFile('upload')) {
            $originName = $request->file('upload')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('upload')->getClientOriginalExtension();
            $fileName = $fileName . '_' . time() . '.' . $extension;
            $request->file('upload')->move(public_path('media'), $fileName);
            $url = asset('media/' . $fileName);
            return response()->json(['fileName' => $fileName, 'uploaded' => 1, 'url' => $url]);
        }
    }

    /**
     * Store a newly created resource in storage.
     */

    public function store(ArticleRequest $request)
    {
        $path = '';
        if ($request->hasFile('files')) {
            $image = $request->file('files');
            $path = Storage::disk('public')->putFile('articles', $image);
        }

        $article = Article::create([
            'title' => $request->input('title'),
            'shortDescription' => $request->input('shortDescription'),
            'content' => $request->input('content'),
            'author' => 'Your Author Name',
            'image' => $path,
            'category_id' => $request->input('category_id'),
            'user_id' => $request->user()->id,
        ]);

        $articleId = $request->tags;
        $article->tags()->attach($articleId);

        return redirect()->back()->with('success', 'Article created successfully');
    }

    //storeSchedule task
    public function storeSchedule(ArticleRequest $request)
    {
        $path = '';
        if ($request->hasFile('files')) {
            $image = $request->file('files');
            $path = Storage::disk('public')->putFile('articles', $image);
        }

        $article = Article::create([
            'title' => $request->input('title'),
            'shortDescription' => $request->input('shortDescription'),
            'content' => $request->input('content'),
            'author' => 'Your Author Name',
            'image' => $path,
            'schedule_at' => $request->schedule_at,
            'status' => 'dislable',
            'category_id' => $request->input('category_id'),
            'user_id' => $request->user()->id,
        ]);

        $articleId = $request->tags;
        if ($articleId) {
            $article->tags()->attach($articleId);
        }

        return redirect()->back()->with('success', 'Article created successfully');
    }
    /**
     * Display the specified resource.
     */

    public function search(Request $request)
    {
        $articles = Article::filter($request->all())->get();

        return view('admin.article.index', compact('articles'));
    }

    public function show(string $id)
    {
        $article = Article::with('tags')->findOrFail($id);
        return view('admin.article.detail', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $categories = Category::all();
        $tags = Tag::all();
        $article = Article::with('tags')->findOrFail($id);
        return view('admin.article.editArticle', compact('article', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     */

    public function update(ArticleUpdateRequest $request, string $id)
    {
        $path = '';
        $article = Article::findOrFail($id);
        if ($request->hasFile('files')) {
            $image = $request->file('files');
            $path = Storage::disk('public')->putFile('articles', $image);
            if (Storage::exists($article->image)) {
                Storage::delete($article->image);
            }
        }
        $article->update([
            'title' => $request->input('title'),
            'shortDescription' => $request->input('shortDescription'),
            'content' => $request->input('content'),
            'author' => 'Your Author Name',
            'image' => $path != '' ? $path : $article->image,
            'category_id' => $request->input('category_id'),
        ]);

        $articleId = $request->tags;
        if ($articleId) {
            $article->tags()->sync($articleId);
        }

        return redirect()->back()->with('success', 'Article updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $article = Article::findOrFail($id);
        if ($article) {
            $article->tags()->delete();
            $article->delete();
        }
        return back()->with('success', 'Delete an article sucessfully');
    }
}

app/Http/Controllers/Writer/ArticleWriterController.php
<?php

namespace App\Http\Controllers\Writer;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\Category;
use App\Models\Tag;
use Illuminate\Foundation\Auth\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ArticleWriterController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $articles = Article::with('tags')->where('user_id', Auth::user()->id)->get();
        $categories = Category::all();
        $tags = Tag::all();
        return view('writer.article.index', compact('articles', 'categories', 'tags'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('writer.article.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ArticleRequest $request)
    {
        $path = '';
        if ($request->hasFile('files')) {
            $image = $request->file('files');
            $path = Storage::disk('public')->putFile('articles', $image);
        }

        $article = Article::create([
            'title' => $request->input('title'),
            'shortDescription' => $request->input('shortDescription'),
            'content' => $request->input('content'),
            'author' => 'Your Author Name',
            'image' => $path,
            'category_id' => $request->input('category_id'),
            'user_id' => $request->user()->id,
        ]);

        $articleId = $request->tags;
        $article->tags()->attach($articleId);

        return redirect()->back()->with('success', 'Article created successfully');
    }

    /**
     * Display the specified resource.
     */
    public function uploadTextImage(Request $request)
    {
        if ($request->hasFile('upload')) {
            $originName = $request->file('upload')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('upload')->getClientOriginalExtension();
            $fileName = $fileName . '_' . time() . '.' . $extension;
            $request->file('upload')->move(public_path('media'), $fileName);
            $url = asset('media/' . $fileName);
            return response()->json(['fileName' => $fileName, 'uploaded' => 1, 'url' => $url]);
        }
    }

    public function show(string $id)
    {
        $article = Article::with('tags')->findOrFail($id);
        $articleSameCategories = Article::where('category_id', $article->category_id)
            ->where('id', '!=', $article->id)
            ->get();

        $articleSameTags = Article::whereHas('tags', function ($query) use ($article) {
            $query->whereIn('tags.id', $article->tags->pluck('id'));
        })
            ->where('articles.id', '!=', $article->id)
            ->get();

        return view('writer.article.detail', compact('article', 'articleSameCategories', 'articleSameTags'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $categories = Category::all();
        $tags = Tag::all();
        $article = Article::with('tags')->findOrFail($id);
        return view('admin.article.editArticle', compact('article', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $path = '';
        $article = Article::findOrFail($id);
        if ($request->hasFile('files')) {
            $image = $request->file('files');
            $path = Storage::disk('public')->putFile('articles', $image);
            if (Storage::exists($article->image)) {
                Storage::delete($article->image);
            }
        }
        $article->update([
            'title' => $request->input('title'),
            'shortDescription' => $request->input('shortDescription'),
            'content' => $request->input('content'),
            'author' => 'Your Author Name',
            'image' => $path != '' ? $path : $article->image,
            'category_id' => $request->input('category_id'),
        ]);

        $articleId = $request->tags;
        if ($articleId) {
            $article->tags()->sync($articleId);
        }

        return redirect()->back()->with('success', 'Article updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $article = Article::findOrFail($id);
        if ($article) {
            $article->tags()->delete();
            $article->delete();
        }
        return back()->with('success', 'Delete an article sucessfully');
    }
}

app/Http/Controllers/Writer/TagController.php
<?php

namespace App\Http\Controllers\Writer;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Tag;
use App\Models\Article;
use App\Http\Requests\TagRequest;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $tags = Tag::all();
        $articles = Article::all();
        return view('admin.tag.index', compact(['tags', 'articles']));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(TagRequest $request)
    {
        $tags = Tag::create([
            'name' => $request->input(['name']),
            'description' => $request->input(['description']),
        ]);
        $articleIds = $request->articles;
        if ($articleIds) {
            $tags->articles()->attach($articleIds);
        }
        return back()->with('success', 'create a tag successfully');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    public function search(Request $request)
    {
        $articles = Article::all();
        $tags = Tag::filter($request->all())->get();

        return view('admin.tag.index', compact(['tags', 'articles']));
    }
    /**
     * Update the specified resource in storage.
     */
    public function update(TagRequest $request, string $id)
    {
        $tags = Tag::findOrFail($id);
        $tags->update([
            'name' => $request->input(['name']),
            'description' => $request->input(['description']),
        ]);
        $articleIds = $request->articles;
        if ($articleIds) {
            $tags->articles()->sync($articleIds);
        }
        return back()->with('success', 'Update a tag successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $tags = Tag::findOrFail($id);
        if ($tags) {
            $tags->delete();
            $tags->articles()->detach();
        }
        return back()->with('success', 'Delete a tag successfully');
    }
}

resources/views/writer/article/create.blade.php
@extends('dashboard')

@section('content')
    <div class="m-20">


        @if ($errors->any())
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4">
                {{ session('success') }}
            </div>
        @endif

        <form class="mx-auto mt-12" action="{{ route('writerArticle.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="mb-4">
                <label for="title" class="block text-gray-700 font-bold mb-2">Title:</label>
                <input type="text" class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" name="title"
                    id="title">
            </div>

            <!-- Textarea without sizing class -->
            <div class="mb-4">
                <label class="block text-gray-700 font-bold mb-2" for="shortDescription">Short Description:</label>
                <textarea class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" id="shortDescription"
                    name="shortDescription" rows="3"></textarea>
            </div>

            <div class="mb-4">
                <label for="category_id" class="block text-gray-700 font-bold mb-2">Select a Category:</label>
                <select class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" id="category_id"
                    name="category_id">
                    <option>Choose an option:</option>
                    @foreach ($categories as $key => $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-4">
                <label for="editor" class="block text-gray-700 font-bold mb-2">Write Content:</label>
                <textarea id="editor" name="content"></textarea>
            </div>

            <div class="mb-4">
                <label for="tags" class="block text-gray-700 font-bold mb-2">Select Tags:</label>
                <select multiple class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" id="tags"
                    name="tags[]">
                    @foreach ($tags as $tag)
                        <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-6">
                <div class="mb-3">
                    <label for="formFile" class="block text-gray-700 font-bold mb-2">Select an image:</label>
                    <input class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" type="file"
                        id="formFile" name="files" onchange="handleFileSelectStory(event)">
                </div>
                <div id="selectedFiles1"></div>
                <div id="showText"></div>
            </div>

            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Submit
            </button>
        </form>

        <script src="https://cdn.ckeditor.com/ckeditor5/41.1.0/classic/ckeditor.js"></script>
        <script>
            function handleFileSelectStory(e) {
                var selDiv = document.querySelector("#selectedFiles1");
                var showText = document.querySelector("#showText");
                if (!e.target.files || !window.FileReader) return;
                selDiv.innerHTML = "";
                var files = e.target.files;
                var filesArr = Array.prototype.slice.call(files);
                var yourTextImage = '<p class="mb-2">Images that you selected:</p>';
                showText.innerHTML = yourTextImage;
                filesArr.forEach(function(f, i) {
                    var f = files[i];
                    if (!f.type.match("image.*")) {
                        return;
                    }
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        var html = '<img class="max-w-xs" src="' + e.target.result + '"><br clear="left"/>';
                        selDiv.innerHTML += html;
                    }
                    reader.readAsDataURL(f);
                });
            }

            ClassicEditor
                .create(document.querySelector('#editor'), {
                    ckfinder: {
                        uploadUrl: `{{ route('content.image.upload1') . '?_token=' . csrf_token() }}`
                    }
                })
                .then(editor => {
                    console.log(editor);
                })
                .catch(error => {
                    console.error(error);
                });
        </script>
    </div>
@endsection

resources/views/writer/article/edit.blade.php
@extends('dashboard')

@section('content')
    <div class="m-20">


        @if ($errors->any())
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @if (session('success'))
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4">
                {{ session('success') }}
            </div>
        @endif

        <form class="mx-auto mt-12" action="{{ route('writerArticle.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="mb-4">
                <label for="title" class="block text-gray-700 font-bold mb-2">Title:</label>
                <input type="text" class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" name="title"
                    id="title">
            </div>

            <!-- Textarea without sizing class -->
            <div class="mb-4">
                <label class="block text-gray-700 font-bold mb-2" for="shortDescription">Short Description:</label>
                <textarea class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" id="shortDescription"
                    name="shortDescription" rows="3"></textarea>
            </div>

            <div class="mb-4">
                <label for="category_id" class="block text-gray-700 font-bold mb-2">Select a Category:</label>
                <select class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" id="category_id"
                    name="category_id">
                    <option>Choose an option:</option>
                    @foreach ($categories as $key => $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-4">
                <label for="editor" class="block text-gray-700 font-bold mb-2">Write Content:</label>
                <textarea id="editor" name="content"></textarea>
            </div>

            <div class="mb-4">
                <label for="tags" class="block text-gray-700 font-bold mb-2">Select Tags:</label>
                <select multiple class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" id="tags"
                    name="tags[]">
                    @foreach ($tags as $tag)
                        <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="mb-6">
                <div class="mb-3">
                    <label for="formFile" class="block text-gray-700 font-bold mb-2">Select an image:</label>
                    <input class="form-control w-full px-3 py-2 border border-gray-300 rounded-md" type="file"
                        id="formFile" name="files" onchange="handleFileSelectStory(event)">
                </div>
                <div id="selectedFiles1"></div>
                <div id="showText"></div>
            </div>

            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Submit
            </button>
        </form>

        <script src="https://cdn.ckeditor.com/ckeditor5/41.1.0/classic/ckeditor.js"></script>
        <script>
            function handleFileSelectStory(e) {
                var selDiv = document.querySelector("#selectedFiles1");
                var showText = document.querySelector("#showText");
                if (!e.target.files || !window.FileReader) return;
                selDiv.innerHTML = "";
                var files = e.target.files;
                var filesArr = Array.prototype.slice.call(files);
                var yourTextImage = '<p class="mb-2">Images that you selected:</p>';
                showText.innerHTML = yourTextImage;
                filesArr.forEach(function(f, i) {
                    var f = files[i];
                    if (!f.type.match("image.*")) {
                        return;
                    }
                    var reader = new FileReader();
                    reader.onload = function(e) {
                        var html = '<img class="max-w-xs" src="' + e.target.result + '"><br clear="left"/>';
                        selDiv.innerHTML += html;
                    }
                    reader.readAsDataURL(f);
                });
            }

            ClassicEditor
                .create(document.querySelector('#editor'), {
                    ckfinder: {
                        uploadUrl: `{{ route('content.image.upload1') . '?_token=' . csrf_token() }}`
                    }
                })
                .then(editor => {
                    console.log(editor);
                })
                .catch(error => {
                    console.error(error);
                });
        </script>
    </div>
@endsection

resources/views/writer/article/index.blade.php
@extends('dashboard')

@section('content')
    <a href="{{ route('writerArticle.create') }}"
        class="ml-20 text-white bg-gradient-to-br from-purple-600 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Create
        an article</a>
    <div class="mt-12 flex justify-between items-center mx-36 gap-6">
        <div class="w-[70%] p-4">
            @foreach ($articles as $article)
                <div
                    class="relative block mb-4 bg-white hover:bg-gray-100 transition duration-200 shadow-lg rounded-lg overflow-hidden group">
                    <div class="flex gap-4">
                        <div class="w-[30%]">
                            <img class="w-full h-auto object-cover" src="{{ Storage::url($article->image) }}"
                                alt="Article Image">
                        </div>
                        <div class="w-[70%] p-4">
                            <h1 class="font-bold text-xl mb-2">{{ $article->title }}</h1>
                            <p class="text-gray-700">{{ $article->shortDescription }}</p>
                        </div>
                    </div>
                    <div
                        class="absolute bottom-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                        <a href="{{ route('show.article', ['id' => $article->id]) }}"
                            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                            Detail
                        </a>
                        <a href="{{ route('writerArticle.edit', ['writerArticle' => $article->id]) }}"
                            class="bg-yellow-500 hover:bg-yellow-700 text-white font-bold py-2 px-4 rounded">
                            Edit
                        </a>
                        <form action="{{ route('writerArticle.destroy', ['writerArticle' => $article->id]) }}"
                            method="POST">
                            @csrf
                            @method('DELETE')
                            <button type="submit"
                                class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                                Delete
                            </button>
                        </form>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection