routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\User\ArticleUserController;
use App\Http\Controllers\User\CategoryUserController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Writer\TagController;
use App\Http\Controllers\Writer\ArticleWriterController;
use App\Http\Controllers\User\LikeController;
use App\Http\Controllers\User\CommentController;
use App\Http\Controllers\languageController;
use App\Http\Controllers\SocializationController;

//Route user dont need to login
Route::get('/', [ArticleUserController::class, 'index'])->name('homepage');
Route::get('/category/detail/{id}', [CategoryUserController::class, 'detail'])->name('detail.category');
Route::get('/article/detail/{id}', [ArticleUserController::class, 'show'])->name('show.article');
Route::get('/article/search', [ArticleUserController::class, 'search'])->name('article.search.user');
//route to stranslate
Route::get('/translate/{language}', [LanguageController::class, 'translate'])->name('translate.language');
//route to login with google
Route::get('/redirect/google', [SocializationController::class, 'redirectGoogle'])->name('redirect.google');
Route::get('/auth/google/callback', [SocializationController::class, 'callback']);


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    // make a read
    Route::get('/makeRead/{notification}', [NotificationController::class, 'makeRead'])->name('makeRead');
    //route like an article
    Route::post('/articles/{articleId}/like', [LikeController::class, 'likePost'])->name('like');
    Route::delete('/articles/{articleId}/like', [LikeController::class, 'unlikePost'])->name('unlike');
    Route::resources([
        'comment' => CommentController::class,
    ]);
});

//Route of writer role
Route::prefix('writer')->middleware(['auth', 'checkRole:Writer'])->group(function () {
    Route::post('upload-textImage1', [ArticleWriterController::class, 'uploadTextImage'])->name('content.image.upload1');
    Route::resources([
        'writerArticle' => ArticleWriterController::class,
    ]);
});


//Route of admin role
Route::prefix('admin')->middleware(['auth', 'checkRole:Admin'])->group(function () {
    //Article controller route
    Route::get('edit-post', [ArticleController::class, 'edit2'])->name('edit2');
    Route::get('/create/article', [ArticleController::class, 'crate'])->name('article.create.differ');
    Route::get('/list-schedule', [ArticleController::class, 'listSchedule'])->name('article.list.schedule');
    Route::get('/create-schedule', [ArticleController::class, 'createSchedule'])->name('article.create.schedule');
    Route::post('/store-schedule', [ArticleController::class, 'storeSchedule'])->name('article.store.schedule');
    Route::get('/search-article', [ArticleController::class, 'search'])->name('article.search');
    Route::post('upload-textImage', [ArticleController::class, 'uploadTextImage'])->name('content.image.upload');

    //Routes to search by model filler
    Route::get('/search-user', [UserController::class, 'search'])->name('user.search');
    Route::get('/search-tag', [TagController::class, 'search'])->name('tag.search');
    Route::get('/search-category', [CategoryController::class, 'search'])->name('category.search');
    Route::get('/searc-notification', [NotificationController::class, 'search'])->name('notification.search');

    //all route resource
    Route::resources([
        'categories' => CategoryController::class,
        'users' => UserController::class,
        'article' => ArticleController::class,
        'notification' => NotificationController::class,
        'tag' => TagController::class,
    ]);
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use EloquentFilter\Filterable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes, Filterable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'provider_id',
        'password',
        'provider',
        'image',
        'role',
    ];
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }
    public function likes(): HasMany
    {
        return $this->hasMany(Like::class);
    }

    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(UserRequest $request)
    {
        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => $request->input('password'),
            'role' => $request->role,
        ]);

        return back()->with('success', 'Create user successfully');
    }
    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }
    public function search(Request $request)
    {
        $users = User::filter($request->all())->get();

        return view('admin.user.index', compact('users'));
    }
    /**
     * Update the specified resource in storage.
     */
    public function update(UserUpdateRequest $request, string $id)
    {
        $user = User::findOrFail($id);

        $user->update([
            'name' => $request->input('name'),
            'role' => $request->input('role'), // Bạn cần sử dụng input() để truy cập vào dữ liệu từ request
        ]);

        return back()->with('success', 'Updated user successfully');
    }


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $user = User::findOrFail($id);
        if ($user) {
            $user->delete();
        }

        return back()->with('success', 'Deleted user successfully');
    }
}

app/Http/Controllers/User/ArticleUserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\NotificationUser;
use Illuminate\Support\Facades\Auth;

class ArticleUserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $articles = Article::with('tags')->get();
        
        return view('user.homepage', compact('articles'));
    }

    public function show(string $id)
    {
        $article = Article::with(['comments.user'])->findOrFail($id);
        $articleSameCategories = Article::where('category_id', $article->category_id)
            ->where('id', '!=', $article->id)
            ->get();

        $articleSameTags = Article::whereHas('tags', function ($query) use ($article) {
            $query->whereIn('tags.id', $article->tags->pluck('id'));
        })
            ->where('articles.id', '!=', $article->id)
            ->get();

        return view('user.detail', compact('article', 'articleSameCategories', 'articleSameTags'));
    }

    public function search(Request $request)
    {
        $articles = Article::filter($request->all())->get();

        return view('user.homepage', compact('articles'));
    }
}

app/Http/Controllers/User/CategoryUserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Article;

class CategoryUserController extends Controller
{
    public function detail($id)
    {
        $articles = Article::where('category_id', $id)->get();
        
        return view('user.homepage', compact('articles'));
    }
}

app/Http/Controllers/User/CommentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Comment;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $comment = Comment::create([
            'content' => $request->content,
            'user_id' => Auth::user()->id,
            'article_id' => $request->article_id
        ]);
        return back();
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/User/LikeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Like;


class LikeController extends Controller
{

    public function likePost($articleId)
    {
        $like = new Like();
        $like->user_id = auth()->id();
        $like->article_id = $articleId;
        $like->save();

        return back();
    }

    public function unlikePost($articleId)
    {
        $article =  Article::findOrFail($articleId);
        $article->likes()->where('user_id', auth()->id())->delete();

        return back();
    }
}

resources/views/user/detail.blade.php
@extends('dashboard')

@section('content')
    <h1 class="font-bold text-xl mb-2 m-10">Detail page</h1>
    <div class="mt-12 flex justify-between items-start mx-36 gap-6">

        <div class="w-[70%] p-4">
            <div class="justify-between items-center">
                <img class="w-[70%]" src="{{ Storage::url($article->image) }}" alt="">
            </div>

            <h1 class="font-bold text-xl mb-2">{{ $article->title }}</h1>

            <div>
                {!! $article->content !!}
            </div>
            <p>Articles with the same category</p>
            @foreach ($articleSameTags as $article)
                <a href="{{ route('show.article', ['id' => $article->id]) }}"
                    class="block mb-4 bg-white hover:bg-gray-100 transition duration-200 shadow-lg rounded-lg overflow-hidden">
                    <div class="flex gap-4">
                        <div class="w-[30%]">
                            <img class="w-full h-auto object-cover" src="{{ Storage::url($article->image) }}"
                                alt="Article Image">
                        </div>
                        <div class="w-[70%] p-4">
                            <h1 class="font-bold text-xl mb-2">{{ $article->title }}</h1>
                            <p class="text-gray-700">{{ $article->shortDescription }}</p>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
        <div class="bg-blue-100 w-[27%] text-black p-4 rounded-lg shadow-lg">
            <p>Articles with the same tag</p>
            @foreach ($articleSameCategories as $article)
                <a href="{{ route('show.article', ['id' => $article->id]) }}"
                    class="block mb-4 bg-white hover:bg-gray-100 transition duration-200 shadow-lg rounded-lg overflow-hidden">
                    <div class="flex gap-4">
                        <div class="w-[30%]">
                            <img class="w-full h-auto object-cover" src="{{ Storage::url($article->image) }}"
                                alt="Article Image">
                        </div>
                        <div class="w-[70%] p-4">
                            <h1 class="font-bold text-xl mb-2">{{ $article->title }}</h1>
                            <p class="text-gray-700">{{ $article->shortDescription }}</p>
                        </div>
                    </div>
                </a>
            @endforeach
        </div>
    </div>

    <section class="bg-white dark:bg-gray-900 py-8 lg:py-16 antialiased">
        <div class="max-w-2xl mx-auto px-4">
            <div class="flex justify-between items-center mb-6">
                <h2 class="text-lg lg:text-2xl font-bold text-gray-900 dark:text-white">Discussion (20)</h2>
            </div>
            <form class="mb-6" action="{{ route('comment.store') }}" method="post">
                @csrf
                <div
                    class="py-2 px-4 mb-4 bg-white rounded-lg rounded-t-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
                    <label for="comment" class="sr-only">Your comment</label>
                    <input type="text" class="hidden" name="article_id" value="{{ $article->id }}">
                    <textarea id="comment" rows="6"
                        class="px-0 w-full text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800"
                        placeholder="Write a comment..." name="content"></textarea>
                </div>

                <button type="submit" class="bg-blue-900">Post</button>
            </form>
            @foreach ($article->comments as $comment)
                <article class="p-6 text-base bg-white rounded-lg dark:bg-gray-900">
                    <footer class="flex justify-between items-center mb-2">
                        <div class="flex items-center">
                            <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white font-semibold">
                                <img class="mr-2 w-6 h-6 rounded-full"
                                    src="https://flowbite.com/docs/images/people/profile-picture-2.jpg"
                                    alt="Michael Gough">{{$comment->user->name}}</p>
                            <p class="text-sm text-gray-600 dark:text-gray-400"><time pubdate datetime="2022-02-08"
                                    title="February 8th, 2022">{{ $comment->created_at}}</time></p>
                        </div>
                        <button id="dropdownComment1Button" data-dropdown-toggle="dropdownComment1"
                            class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-500 dark:text-gray-400 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-50 dark:bg-gray-900 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                            type="button">
                            <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                viewBox="0 0 16 3">
                                <path
                                    d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z" />
                            </svg>
                            <span class="sr-only">Comment settings</span>
                        </button>
                        <!-- Dropdown menu -->

                    </footer>

                    <p class="text-gray-500 dark:text-gray-400">{{ $comment->content}}</p>
       
                </article>
            @endforeach



        </div>
    </section>
@endsection

resources/views/user/homepage.blade.php
@extends('dashboard')
@section('content')
<h1 class="ml-6 font-bold text-center text-2xl">List of articles</h1>
    <div class="mt-12 flex justify-between items-center mx-36 gap-6">
        <div class="w-[70%] p-4">
            @foreach ($articles as $article)
                <div
                    class="relative block mb-4 bg-white hover:bg-gray-100 transition duration-200 shadow-lg rounded-lg overflow-hidden group">
                    <div class="flex gap-4">
                        <div class="w-[30%]">
                            <img class="w-full h-auto object-cover" src="{{ Storage::url($article->image) }}"
                                alt="Article Image">
                        </div>
                        <div class="w-[70%] p-4">
                            <h1 class="font-bold text-xl mb-2">{{ $article->title }}</h1>
                            <p class="text-gray-700">{{ $article->shortDescription }}</p>
                        </div>
                    </div>
                    <div
                        class="absolute bottom-4 right-4 flex gap-2 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                        <a href="{{ route('show.article', ['id' => $article->id]) }}"
                            class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                            Detail
                        </a>
                        @auth
                            @if ($article->isLikedBy())
                                <div class="flex justify-between items-center">
                                    <form action="{{ route('unlike', ['articleId' => $article->id]) }}"
                                        id="toggle1{{ $article->id }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit"
                                            class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">
                                            Unlike
                                        </button>
                                    </form>
                                    <p class="text-white p-1 bg-gray-500 rounded-md">{{ $article->likes->count() }} Like</p>
                                </div>
                            @else
                                <div class="flex justify-between items-center">
                                    <form action="{{ route('like', ['articleId' => $article->id]) }}"
                                        id="toggle2{{ $article->id }}" method="POST">
                                        @csrf
                                        <button type="submit"
                                            class="text-gray-900 bg-gradient-to-r from-lime-200 via-lime-400 to-lime-500 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-lime-300 dark:focus:ring-lime-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">
                                            Like
                                        </button>
                                    </form>
                                    <p class="text-white p-1 bg-gray-500 rounded-md">{{ $article->likes->count() }} Like</p>
                                </div>
                            @endif
                        @endauth
                    </div>
                </div>
            @endforeach
        </div>
    </div>
@endsection