routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ArticleController;
use App\Http\Controllers\User\ArticleUserController;
use App\Http\Controllers\User\CategoryUserController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\NotificationController;
use App\Http\Controllers\Writer\TagController;
use App\Http\Controllers\Writer\ArticleWriterController;
use App\Http\Controllers\User\LikeController;
use App\Http\Controllers\User\CommentController;
use App\Http\Controllers\languageController;
use App\Http\Controllers\SocializationController;

//Route user dont need to login
Route::get('/', [ArticleUserController::class, 'index'])->name('homepage');
Route::get('/category/detail/{id}', [CategoryUserController::class, 'detail'])->name('detail.category');
Route::get('/article/detail/{id}', [ArticleUserController::class, 'show'])->name('show.article');
Route::get('/article/search', [ArticleUserController::class, 'search'])->name('article.search.user');
//route to stranslate
Route::get('/translate/{language}', [LanguageController::class, 'translate'])->name('translate.language');
//route to login with google
Route::get('/redirect/google', [SocializationController::class, 'redirectGoogle'])->name('redirect.google');
Route::get('/auth/google/callback', [SocializationController::class, 'callback']);


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
    // make a read
    Route::get('/makeRead/{notification}', [NotificationController::class, 'makeRead'])->name('makeRead');
    //route like an article
    Route::post('/articles/{articleId}/like', [LikeController::class, 'likePost'])->name('like');
    Route::delete('/articles/{articleId}/like', [LikeController::class, 'unlikePost'])->name('unlike');
    Route::resources([
        'comment' => CommentController::class,
    ]);
});

//Route of writer role
Route::prefix('writer')->middleware(['auth', 'checkRole:Writer'])->group(function () {
    Route::post('upload-textImage1', [ArticleWriterController::class, 'uploadTextImage'])->name('content.image.upload1');
    Route::resources([
        'writerArticle' => ArticleWriterController::class,
    ]);
});


//Route of admin role
Route::prefix('admin')->middleware(['auth', 'checkRole:Admin'])->group(function () {
    //Article controller route
    Route::get('edit-post', [ArticleController::class, 'edit2'])->name('edit2');
    Route::get('/create/article', [ArticleController::class, 'crate'])->name('article.create.differ');
    Route::get('/list-schedule', [ArticleController::class, 'listSchedule'])->name('article.list.schedule');
    Route::get('/create-schedule', [ArticleController::class, 'createSchedule'])->name('article.create.schedule');
    Route::post('/store-schedule', [ArticleController::class, 'storeSchedule'])->name('article.store.schedule');
    Route::get('/search-article', [ArticleController::class, 'search'])->name('article.search');
    Route::post('upload-textImage', [ArticleController::class, 'uploadTextImage'])->name('content.image.upload');

    //Routes to search by model filler
    Route::get('/search-user', [UserController::class, 'search'])->name('user.search');
    Route::get('/search-tag', [TagController::class, 'search'])->name('tag.search');
    Route::get('/search-category', [CategoryController::class, 'search'])->name('category.search');
    Route::get('/searc-notification', [NotificationController::class, 'search'])->name('notification.search');

    //all route resource
    Route::resources([
        'categories' => CategoryController::class,
        'users' => UserController::class,
        'article' => ArticleController::class,
        'notification' => NotificationController::class,
        'tag' => TagController::class,
    ]);
});

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use EloquentFilter\Filterable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes, Filterable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'provider_id',
        'password',
        'provider',
        'image',
        'role',
    ];
    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }
    public function likes(): HasMany
    {
        return $this->hasMany(Like::class);
    }

    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\UserRequest;
use App\Http\Requests\UserUpdateRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::all();
        return view('admin.user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(UserRequest $request)
    {
        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => $request->input('password'),
            'role' => $request->role,
        ]);

        return back()->with('success', 'Create user successfully');
    }
    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }
    public function search(Request $request)
    {
        $users = User::filter($request->all())->get();

        return view('admin.user.index', compact('users'));
    }
    /**
     * Update the specified resource in storage.
     */
    public function update(UserUpdateRequest $request, string $id)
    {
        $user = User::findOrFail($id);

        $user->update([
            'name' => $request->input('name'),
            'role' => $request->input('role'), // Bạn cần sử dụng input() để truy cập vào dữ liệu từ request
        ]);

        return back()->with('success', 'Updated user successfully');
    }


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $user = User::findOrFail($id);
        if ($user) {
            $user->delete();
        }

        return back()->with('success', 'Deleted user successfully');
    }
}

app/Http/Controllers/User/ArticleUserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Article;
use App\Models\NotificationUser;
use Illuminate\Support\Facades\Auth;

class ArticleUserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $articles = Article::with('tags')->get();
        
        return view('user.homepage', compact('articles'));
    }

    public function show(string $id)
    {
        $article = Article::with(['comments.user'])->findOrFail($id);
        $articleSameCategories = Article::where('category_id', $article->category_id)
            ->where('id', '!=', $article->id)
            ->get();

        $articleSameTags = Article::whereHas('tags', function ($query) use ($article) {
            $query->whereIn('tags.id', $article->tags->pluck('id'));
        })
            ->where('articles.id', '!=', $article->id)
            ->get();

        return view('user.detail', compact('article', 'articleSameCategories', 'articleSameTags'));
    }

    public function search(Request $request)
    {
        $articles = Article::filter($request->all())->get();

        return view('user.homepage', compact('articles'));
    }
}

app/Http/Controllers/User/CategoryUserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Article;

class CategoryUserController extends Controller
{
    public function detail($id)
    {
        $articles = Article::where('category_id', $id)->get();
        
        return view('user.homepage', compact('articles'));
    }
}

app/Http/Controllers/User/CommentController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Comment;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $comment = Comment::create([
            'content' => $request->content,
            'user_id' => Auth::user()->id,
            'article_id' => $request->article_id
        ]);
        return back();
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

app/Http/Controllers/User/LikeController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Like;


class LikeController extends Controller
{

    public function likePost($articleId)
    {
        $like = new Like();
        $like->user_id = auth()->id();
        $like->article_id = $articleId;
        $like->save();

        return back();
    }

    public function unlikePost($articleId)
    {
        $article =  Article::findOrFail($articleId);
        $article->likes()->where('user_id', auth()->id())->delete();

        return back();
    }
}

resources/views/layouts/user/header.blade.php
<header class='shadow-md bg-white font-sans tracking-wide relative z-50'>
    <section
        class='flex items-center lg:justify-center flex-wrap gap-5 relative py-3 px-10 border-gray-200 border-b lg:min-h-[80px] max-lg:min-h-[60px]'>
        <a href="javascript:void(0)"><img src="https://readymadeui.com/readymadeui.svg" alt="logo"
                class='md:w-[170px] w-36' />
        </a>


    </section>

    <div class='flex flex-wrap py-3.5 px-10 overflow-x-auto'>

        <div id="collapseMenu"
            class='w-full max-lg:hidden lg:!block max-lg:before:fixed max-lg:before:bg-black max-lg:before:opacity-50 max-lg:before:inset-0 max-lg:before:z-50'>
            <button id="toggleClose" class='lg:hidden fixed top-2 right-4 z-[100] rounded-full bg-white p-3'>
                <svg xmlns="http://www.w3.org/2000/svg" class="w-4 fill-black" viewBox="0 0 320.591 320.591">
                    <path
                        d="M30.391 318.583a30.37 30.37 0 0 1-21.56-7.288c-11.774-11.844-11.774-30.973 0-42.817L266.643 10.665c12.246-11.459 31.462-10.822 42.921 1.424 10.362 11.074 10.966 28.095 1.414 39.875L51.647 311.295a30.366 30.366 0 0 1-21.256 7.288z"
                        data-original="#000000"></path>
                    <path
                        d="M287.9 318.583a30.37 30.37 0 0 1-21.257-8.806L8.83 51.963C-2.078 39.225-.595 20.055 12.143 9.146c11.369-9.736 28.136-9.736 39.504 0l259.331 257.813c12.243 11.462 12.876 30.679 1.414 42.922-.456.487-.927.958-1.414 1.414a30.368 30.368 0 0 1-23.078 7.288z"
                        data-original="#000000"></path>
                </svg>
            </button>

            <ul
                class='lg:flex lg:justify-center lg:gap-x-10 max-lg:space-y-3 max-lg:fixed max-lg:bg-white max-lg:w-1/2 max-lg:min-w-[300px] max-lg:top-0 max-lg:left-0 max-lg:p-6 max-lg:h-full max-lg:shadow-md max-lg:overflow-auto z-50'>
                <li class='mb-6 hidden max-lg:block'>
                    <a href="javascript:void(0)"><img src="https://readymadeui.com/readymadeui.svg" alt="logo"
                            class='w-36' />
                    </a>
                <li class='max-lg:border-b max-lg:py-3'><a href='javascript:void(0)'
                        class='hover:text-[#007bff] text-[#007bff] font-bold text-[15px] block'>Home</a></li>

                @foreach ($categories as $key => $category)
                    <li class='max-lg:border-b max-lg:py-3'><a
                            href='{{ route('detail.category', ['id' => $category->id]) }}'
                            class='hover:text-[#007bff] text-gray-500 font-bold text-[15px] block'>{{ $category->name }}</a>
                    </li>
                @endforeach
            </ul>
        </div>


    </div>
</header>

resources/views/layouts/user/nav.blade.php
<nav class="bg-white border-gray-200 dark:bg-gray-900">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
        <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
            <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
            <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Flowbite</span>
        </a>

        <div class="flex items-center md:order-2 space-x-1 md:space-x-0 rtl:space-x-reverse">
            @auth
                <select
                    class="py-3 mr-2 px-4 pe-9 block w-full bg-gray-100 border-transparent rounded-lg text-sm focus:border-blue-500 focus:ring-blue-500 disabled:opacity-50 disabled:pointer-events-none dark:bg-neutral-700 dark:border-transparent dark:text-neutral-400 dark:focus:ring-neutral-600">
                    <option selected="">Hello: {{ Auth::user()->name }}</option>
                </select>
                <a class="m-4 bg-blue-500 rounded-lg p-2 text-white" href="{{ route('writerArticle.index') }}">View my all
                    articles </a>
                <form method="POST" action="{{ route('logout') }}">
                    @csrf
                    <button class="p-3 bg-yellow-200 rounded-lg border-gray-200" type="submit">Logout</button>
                </form>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle ml-4" type="button" id="dropdownMenuButton"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Notification
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        @foreach (Auth::user()->notifications as $noti)
                            <div class="flex justify-between items-center">
                                <a class="dropdown-item" href="#">{{ $noti->data['message']}}</a>
                                <a class="bg-blue-200 rounded-lg" href="{{ route('makeRead', ['notification' => $noti->id]) }}">Make a read</a>
                            </div>
                        @endforeach
                    </div>
                </div>
            @endauth
        </div>

        @guest
            <div class=" flex justify-between items-center gap-4">
                <a class="p-3 bg-blue-200 rounded-lg border-gray-200" href="/register">Register</a>
                <a class="p-3 bg-red-200 rounded-lg border-gray-200" href="/login">Login</a>
            </div>
        @endguest

        <button data-collapse-toggle="navbar-language" type="button"
            class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
            aria-controls="navbar-language" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 17 14">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="M1 1h15M1 7h15M1 13h15" />
            </svg>
        </button>
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-language">
    </div>
    </div>
</nav>

resources/views/layouts/user/search.blade.php
<div class="flex gap-12 justify-center items-center py-4">

    <form class="flex items-center w-full max-w-3xl" action="{{ route('article.search.user') }}" method="get">
        <input type="text" class="bg-gray-100 border-2 border-blue-500 p-2 rounded mr-2 w-full" name="title"
            placeholder="Search for title..." aria-label="Search for title">

        <input type="text" class="bg-gray-100 border-2 border-blue-500 p-2 rounded mr-2 w-full" name="author"
            placeholder="Search for author..." aria-label="Search for author">

        <div class="relative mr-2 w-full">
            <select class="bg-gray-100 border-2 border-blue-500 p-2 rounded w-full" name="categoryName">
                <option value="">Search by category</option>
                @foreach ($categories as $key => $category)
                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="relative mr-2 w-full">
            <select class="bg-gray-100 border-2 border-blue-500 p-2 rounded w-full" name="tag">
                <option value="">Search by tag</option>
                @foreach ($tags as $key => $tag)
                    <option value="{{ $tag->name }}">{{ $tag->name }}</option>
                @endforeach
            </select>
        </div>
        <button class="bg-blue-500 hover:bg-blue-600 text-white py-2 px-4 rounded" type="submit">
            Search
        </button>
    </form>
</div>

resources/views/layouts/user/user.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    @include('layouts.user.header')
</body>
</html>